### PR TITLE
Add agencyCode to function calls that require it

### PR DESCRIPTION
**Pull request by stevejameskent**
This resolves the last task of cfpb/hmda-pilot#234

### CODE REVIEW

**Comment by LinuxBozo** [comment]
@stevejameskent @doelleri watch these pulls. This was against `master` not a milestone branch. So now this commit is missing from milestone6.

**Comment by doelleri** [comment]
Aw crap. It's hard to tell with the first PR after a milestone merge. Do you want to revert and redo?

**Comment by LinuxBozo** [comment]
No, I'll fix manually..

**Comment by LinuxBozo** [comment]
`milestone6` fixed up..

**Pull request merged**
